
steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/quarantine-chipyard-src', '.']

images: ['gcr.io/$PROJECT_ID/quarantine-chipyard-src']
timeout: 86400s # 24hr


